modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="rtestfield"
version="1.0.0"
displayName="Rtestfield+"
description='''Mod criado por PG e Dudu!
Esse mod adiciona funcionalidades incríveis e customizadas ao Minecraft.
Ideal para explorar ideias, testar mecânicas e se divertir.'''

authors="PG e Dudu"

[[dependencies.rtestfield]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.rtestfield]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
